mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "rmall"
  params: "charset=utf8mb4&parseTime=True"



jwt:
  secret_key: "da43ujuvskzap4qk"
  expire: 259200


redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0