mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "rmall"
  params: "charset=utf8mb4&parseTime=True"



jwt:
  secret_key: "da43ujuvskzap4qk"
  expire: 259200


redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

alipay:
  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  APPID: 沙箱中的APPID
  # 商户私钥，您的PKCS8格式RSA2私钥
  RSA_PRIVATE_KEY: 应用私钥
  # 支付宝支付公钥
  ALIPAY_PUBLIC_KEY: 支付宝公钥（通过应用公钥换取的值）
  # 异步回调地址 必须外网能够访问（这里需要配置内网穿透），当支付成功后会调用该API
  notify_url: http://hpzekg.natappfree.cc/alipay/pay/callback
  # 同步回调地址 必须外网能够访问
  return_url:
  # 网关（注意沙箱网关和正式网关的区别，这里填写沙箱环境下的网关）
  URL: https://openapi.alipaydev.com/gateway.do
  # 编码
  CHARSET: UTF-8
  # 返回数据格式
  FORMAT: json
  # 日志地址
  log_path: /log
  # RSA2
  SIGNTYPE: RSA2