basePath: /
definitions:
  request.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  request.RegisterReq:
    properties:
      email:
        type: string
      mobile:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - mobile
    - password
    - username
    type: object
  response.LoginResp:
    properties:
      expire:
        description: 过期时间
        type: integer
      token:
        type: string
    type: object
  response.RegisterResp:
    properties:
      email:
        type: string
      id:
        type: integer
      mobile:
        type: string
      username:
        type: string
    type: object
  response.UserInfo:
    properties:
      email:
        type: string
      id:
        type: integer
      mobile:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 这是一个描述.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: swagger Example API
  version: "1.0"
paths:
  /api/v1/helloworld:
    get:
      consumes:
      - application/json
      description: 测试输出hello,world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello,world
      tags:
      - User
  /api/v1/user/info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取用户信息成功
          schema:
            $ref: '#/definitions/response.UserInfo'
      tags:
      - 用户
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 登录
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/response.LoginResp'
      tags:
      - 用户
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 注册
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/response.RegisterResp'
        "500":
          description: 参数错误
          schema:
            type: string
      tags:
      - 用户
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
